server:
  max-http-header-size: 10485760
  address: 0.0.0.0
  port: 8080


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    connect-timeout: 1s
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 0ms
    timeout: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

